# Generated by Django 5.1.7 on 2025-04-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='category',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('wedding', 'Wedding'), ('nature', 'Nature'), ('street', 'Street'), ('document', 'Documentary')], default='portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='photos',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
